package edu.gatech.seclass.tccart.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import edu.gatech.seclass.tccart.db.Customer;
import edu.gatech.seclass.tccart.db.Transaction;

import edu.gatech.seclass.tccart.db.CustomerDao;
import edu.gatech.seclass.tccart.db.TransactionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig customerDaoConfig;
    private final DaoConfig transactionDaoConfig;

    private final CustomerDao customerDao;
    private final TransactionDao transactionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        transactionDaoConfig = daoConfigMap.get(TransactionDao.class).clone();
        transactionDaoConfig.initIdentityScope(type);

        customerDao = new CustomerDao(customerDaoConfig, this);
        transactionDao = new TransactionDao(transactionDaoConfig, this);

        registerDao(Customer.class, customerDao);
        registerDao(Transaction.class, transactionDao);
    }
    
    public void clear() {
        customerDaoConfig.getIdentityScope().clear();
        transactionDaoConfig.getIdentityScope().clear();
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public TransactionDao getTransactionDao() {
        return transactionDao;
    }

}
